spring:
  thymeleaf:
    cache: false
  cache:
    type: redis
  task:
    execution:
      pool:
        core-size: 10
        queue-capacity: 100
  profiles:
    active: dev
  application:
    name: lvmc-server


management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# tomcat 工作线程池最大设置为 200
server:
  tomcat:
    threads:
      max: 200
  port: 80


logging:
  level:
    root: info


log:
  file:
    path: /home/spring/logs
