spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Enlink@123
    username: enlink
    url: jdbc:mysql://192.168.114.214:33060/ensecdns_admin?characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
  thymeleaf:
    cache: false
  cache:
    type: redis
  task:
    execution:
      pool:
        core-size: 10
        queue-capacity: 100
  profiles:
    active: dev
  application:
    name: lvmc-server

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# tomcat 工作线程池最大设置为 200
server:
  tomcat:
    max-threads: 200
  port: 8080


logging:
  level:
    root: info


log:
  file:
    path: /home/spring/logs