spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=UTC
  thymeleaf:
    cache: false
  cache:
    type: redis
  task:
    execution:
      pool:
        core-size: 10
        queue-capacity: 100
  profiles:
    active: dev
  application:
    name: springboot

management:
  server:
    port: 2012
  metrics:
    enable:
      all: false # all mean all inner metrics
    export:
      prometheus:
        enabled: true
    tags: # user define labels only for inner metrics
      label-1-name: hello
      label-2-name: world
      application: springboot
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "prometheus","health" ]



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# tomcat 工作线程池最大设置为 200
server:
  tomcat:
    max-threads: 200
  port: 8080
  servlet:
    context-path: /lmc
    session:
      cookie:
        name: lmc




logging:
  level:
    root: info